config/routes.rb
Rails.application.routes.draw do
  get 'products/index'

  get 'products/products'

  get 'products/categories'

  post 'products/index'

  root 'products#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products, dependent: :destroy #Siempre el borrado cascada lo lleva has_many
  before_save :control_discount

  def control_discount
    if self.discount.nil?
      self.discount=0
    elsif self.discount<0
      self.discount=0
    elsif self.discount>100
      self.discount=100
    end
  end

  # validate :discount_valid

  # def discount_valid
  #   if self.discount < 0 || self.discount > 100
  #     errors.add(:discount, "El discount debe ser superior a 0 y menor a 100")
  # end

end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	validates :cost, presence: true
	before_save :default_value
	after_destroy :destroy_category


 	scope :all_premium, -> { where(premium: true) }
 	scope :last_n, ->(n) {limit(n)}

	def default_value
		if self.premium!=true 
			self.premium=false
		end
	end
#unless self.premium.present? || self.premium==true


	def destroy_category
		Category.all.each do |i|
			unless i.products.any?
				i.destroy
			end
		end
  	end


  	 def precio_final
  	 	disc=(self.category.discount * self.cost)/100
  	 	self.cost-disc
  	 end



end
	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index

  	if params[:product_name].present? #comprueba si se envio algun parametro
  		@products=Product.where("name like ?", "%#{params[:product_name]}%")

  	else
  		@products=Product.all
  	end

  	if params[:product_cost].present?
  		@products=Product.where(cost:params[:product_cost].to_i)
  	end
  end

  def categories
    @categories=Category.all
  end


  def products
    @products=Product.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tienda</title>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%=products_index_path%>">Index</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= products_products_path %>">Productos <span class="sr-only">(current)</span></a></li>
        <li><a href="<%=products_categories_path %>">Categorias</a></li>
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  	<div class="container">
    	<%= yield %>
	</div>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/products/categories.html.erb
<div class="jumbotron">
	<h1 class="text-center">Categorias</h1>
</div>
<table>
  <tr>
    <th>Categoría</th>
  </tr>

<% @categories.each do |c| %>
  <tr>
	<td><%= c.name  %> </td>
	 </tr>
<% end  %>
</table>

app/views/products/index.html.erb
<div class="jumbotron">
	<h1 class="text-center">Productos y categorias</h1>
</div>
<table>
  <tr>
    <th>Producto</th>
    <th>Categoría</th>
  </tr>

<% @products.each do |p| %>
  <tr>
	<td><%= p.name  %> </td>
	<td><%= p.category.name %>	</td>
	 </tr>
<% end  %>
</table>



<form method="POST" action="<%= products_index_path %>">
	<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
	<input type="text" name="product_name" placeholder="Ingrese nombre:">
	<input type="number" name="product_cost" placeholder="Ingrese precio">
	<input type="submit" name="Buscar">
</form>

app/views/products/products.html.erb
<div class="jumbotron">
	<h1 class="text-center">Productos</h1>
</div>
<table>
  <tr>
    <th>Producto</th>
  </tr>

<% @products.each do |p| %>
  <tr>
	<td><%= p.name  %> </td>
	 </tr>
<% end  %>
</table>